### ISSUE TITLE
Singularity build files are getting written to /tmp

### ISSUE THREAD

**Issue by ionox0** [msk-access/standard_bam_processing#10]
Maybe they aren't large enough to pose an issue? But still, probably better to not use /tmp at all

jx19.cbio.private
```
/tmp/.singularity-build.seIIYk
/tmp/.singularity-build.seIIYk/etc
/tmp/.singularity-build.seIIYk/etc/hosts
/tmp/.singularity-build.seIIYk/etc/adduser.conf
/tmp/.singularity-build.seIIYk/etc/alternatives
```

**Comment by nikhil** [comment]
You can change this by editing SINGULARITY_TMPDIR. See: https://sylabs.io/guides/3.3/user-guide/build_env.html
